// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Autodesk.ACC.CostManagement.Projects.AssetsDuplication {
    public class AssetsDuplicationPostResponse : IAdditionalDataHolder, IParsable 
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The hard_failed_uids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? HardFailedUids { get; set; }
#nullable restore
#else
        public List<Guid?> HardFailedUids { get; set; }
#endif
        /// <summary>The in_flight_uids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? InFlightUids { get; set; }
#nullable restore
#else
        public List<Guid?> InFlightUids { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="AssetsDuplicationPostResponse"/> and sets the default values.
        /// </summary>
        public AssetsDuplicationPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="AssetsDuplicationPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static AssetsDuplicationPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new AssetsDuplicationPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"hard_failed_uids", n => { HardFailedUids = n.GetCollectionOfPrimitiveValues<Guid?>()?.ToList(); } },
                {"in_flight_uids", n => { InFlightUids = n.GetCollectionOfPrimitiveValues<Guid?>()?.ToList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<Guid?>("hard_failed_uids", HardFailedUids);
            writer.WriteCollectionOfPrimitiveValues<Guid?>("in_flight_uids", InFlightUids);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
