// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.CostManagement.V1.Projects.Item.ChangeOrders.Item.Item.CostItemsCopyFrom {
    public enum CostItemsCopyFromPostRequestBody_to
    {
        [EnumMember(Value = "estimated")]
        Estimated,
        [EnumMember(Value = "proposed")]
        Proposed,
        [EnumMember(Value = "submitted")]
        Submitted,
        [EnumMember(Value = "approved")]
        Approved,
        [EnumMember(Value = "committed")]
        Committed,
    }
}
