// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.CostManagement.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    /// <summary>The type of attachment. Possible values: ``Upload``, ``DocsFile``. ``Upload`` is a locally uploaded file and ``DocsFile`` is a file referenced from BIM 360 Docs.</summary>
    public enum Attachment_type
    {
        [EnumMember(Value = "Upload")]
        #pragma warning disable CS1591
        Upload,
        #pragma warning restore CS1591
        [EnumMember(Value = "DocsFile")]
        #pragma warning disable CS1591
        DocsFile,
        #pragma warning restore CS1591
    }
}
