// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.CostManagement.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    /// <summary>The scope of confgiuration</summary>
    public enum CalendarConfiguration_scope
    {
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "project")]
        #pragma warning disable CS1591
        Project,
        #pragma warning restore CS1591
    }
}
