// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.CostManagement.Models {
    /// <summary>The scope of confgiuration</summary>
    public enum CalendarConfigurationCreate_scope
    {
        [EnumMember(Value = "user")]
        User,
        [EnumMember(Value = "project")]
        Project,
    }
}
