// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.CostManagement.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    /// <summary>The aggregate type of the expense. Possible values: `workCompleted`, `materialsOnSite`, `workCompletedQty`.</summary>
    public enum ExpenseImport_aggregateBy
    {
        [EnumMember(Value = "workCompleted")]
        #pragma warning disable CS1591
        WorkCompleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "materialsOnSite")]
        #pragma warning disable CS1591
        MaterialsOnSite,
        #pragma warning restore CS1591
        [EnumMember(Value = "workCompletedQty")]
        #pragma warning disable CS1591
        WorkCompletedQty,
        #pragma warning restore CS1591
    }
}
