// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.CostManagement.Models {
    public enum Markup_type
    {
        [EnumMember(Value = "markup")]
        Markup,
        [EnumMember(Value = "subtotal")]
        Subtotal,
    }
}
