// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Autodesk.ACC.CostManagement.Models {
    public class ModuleSpecificSettings : IAdditionalDataHolder, IParsable 
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The CostItem property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ModuleSpecificSettings_CostItem? CostItem { get; set; }
#nullable restore
#else
        public ModuleSpecificSettings_CostItem CostItem { get; set; }
#endif
        /// <summary>The FormDefinition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ModuleSpecificSettings_FormDefinition? FormDefinition { get; set; }
#nullable restore
#else
        public ModuleSpecificSettings_FormDefinition FormDefinition { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="ModuleSpecificSettings"/> and sets the default values.
        /// </summary>
        public ModuleSpecificSettings()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="ModuleSpecificSettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ModuleSpecificSettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ModuleSpecificSettings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"CostItem", n => { CostItem = n.GetObjectValue<ModuleSpecificSettings_CostItem>(ModuleSpecificSettings_CostItem.CreateFromDiscriminatorValue); } },
                {"FormDefinition", n => { FormDefinition = n.GetObjectValue<ModuleSpecificSettings_FormDefinition>(ModuleSpecificSettings_FormDefinition.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<ModuleSpecificSettings_CostItem>("CostItem", CostItem);
            writer.WriteObjectValue<ModuleSpecificSettings_FormDefinition>("FormDefinition", FormDefinition);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
