// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.CostManagement.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    /// <summary>The object type of the payment reference is associated to. Currently support only &apos;Expense`, `Payment`, `BudgetPayment`.</summary>
    public enum PaymentReferenceCreate_associationType
    {
        [EnumMember(Value = "Payment")]
        #pragma warning disable CS1591
        Payment,
        #pragma warning restore CS1591
        [EnumMember(Value = "BudgetPayment")]
        #pragma warning disable CS1591
        BudgetPayment,
        #pragma warning restore CS1591
        [EnumMember(Value = "Expense")]
        #pragma warning disable CS1591
        Expense,
        #pragma warning restore CS1591
    }
}
