// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.CostManagement.Models {
    /// <summary>Lock state used by ERP integration, default value is ``null``.</summary>
    public enum PaymentUpdate_integrationState
    {
        [EnumMember(Value = "locked")]
        Locked,
        [EnumMember(Value = "integrated")]
        Integrated,
        [EnumMember(Value = "failed")]
        Failed,
    }
}
