// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.CostManagement.Models {
    /// <summary>The object ID of the payment item is associated to. For example, &apos;SCO&apos;, &apos;OCO&apos;, &apos;SOV&apos;, &apos;CostItem&apos;, &apos;SubCostItem&apos; and &apos;MaterialsOnSite&apos;.</summary>
    public enum PaymentSummary_paymentItemAssociationType
    {
        [EnumMember(Value = "SCO")]
        SCO,
        [EnumMember(Value = "OCO")]
        OCO,
        [EnumMember(Value = "SOV")]
        SOV,
        [EnumMember(Value = "CostItem")]
        CostItem,
        [EnumMember(Value = "SubCostItem")]
        SubCostItem,
        [EnumMember(Value = "MaterialsOnSite")]
        MaterialsOnSite,
    }
}
