// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.CostManagement.Models
{
    /// <summary>For modules like ``PCO``/``Cost Item`` that has 2 statuses.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Status_type
    {
        [EnumMember(Value = "Cost")]
        #pragma warning disable CS1591
        Cost,
        #pragma warning restore CS1591
        [EnumMember(Value = "Budget")]
        #pragma warning disable CS1591
        Budget,
        #pragma warning restore CS1591
        [EnumMember(Value = "Both")]
        #pragma warning disable CS1591
        Both,
        #pragma warning restore CS1591
    }
}
