// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.RFIs.V2.Containers.Item.Rfis {
    public enum GetFilterPriorityQueryParameterType
    {
        [EnumMember(Value = "High")]
        High,
        [EnumMember(Value = "Normal")]
        Normal,
        [EnumMember(Value = "Low")]
        Low,
        [EnumMember(Value = "Unspecified")]
        Unspecified,
    }
}
