// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.CostManagement.V1.Projects.Item.WorkflowDefinitions {
    public enum GetAssociationTypeQueryParameterType
    {
        [EnumMember(Value = "OCO")]
        OCO,
        [EnumMember(Value = "RCO")]
        RCO,
        [EnumMember(Value = "PCO")]
        PCO,
        [EnumMember(Value = "SCO")]
        SCO,
        [EnumMember(Value = "RFQ")]
        RFQ,
        [EnumMember(Value = "Contract")]
        Contract,
        [EnumMember(Value = "CostPayment")]
        CostPayment,
        [EnumMember(Value = "BudgetPayment")]
        BudgetPayment,
        [EnumMember(Value = "Expense")]
        Expense,
    }
}
