// <auto-generated/>
#pragma warning disable CS0618
using Autodesk.ACC.FileManagement.Projects.Item.Folders.Item.CustomAttributeDefinitions;
using Autodesk.ACC.FileManagement.Projects.Item.Folders.Item.PermissionsBatchCreate;
using Autodesk.ACC.FileManagement.Projects.Item.Folders.Item.PermissionsBatchDelete;
using Autodesk.ACC.FileManagement.Projects.Item.Folders.Item.PermissionsBatchUpdate;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Autodesk.ACC.FileManagement.Projects.Item.Folders.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \projects\{project-id}\folders\{folder_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFolder_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The customAttributeDefinitions property</summary>
        public global::Autodesk.ACC.FileManagement.Projects.Item.Folders.Item.CustomAttributeDefinitions.CustomAttributeDefinitionsRequestBuilder CustomAttributeDefinitions
        {
            get => new global::Autodesk.ACC.FileManagement.Projects.Item.Folders.Item.CustomAttributeDefinitions.CustomAttributeDefinitionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The permissionsBatchCreate property</summary>
        public global::Autodesk.ACC.FileManagement.Projects.Item.Folders.Item.PermissionsBatchCreate.PermissionsBatchCreateRequestBuilder PermissionsBatchCreate
        {
            get => new global::Autodesk.ACC.FileManagement.Projects.Item.Folders.Item.PermissionsBatchCreate.PermissionsBatchCreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The permissionsBatchDelete property</summary>
        public global::Autodesk.ACC.FileManagement.Projects.Item.Folders.Item.PermissionsBatchDelete.PermissionsBatchDeleteRequestBuilder PermissionsBatchDelete
        {
            get => new global::Autodesk.ACC.FileManagement.Projects.Item.Folders.Item.PermissionsBatchDelete.PermissionsBatchDeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The permissionsBatchUpdate property</summary>
        public global::Autodesk.ACC.FileManagement.Projects.Item.Folders.Item.PermissionsBatchUpdate.PermissionsBatchUpdateRequestBuilder PermissionsBatchUpdate
        {
            get => new global::Autodesk.ACC.FileManagement.Projects.Item.Folders.Item.PermissionsBatchUpdate.PermissionsBatchUpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.ACC.FileManagement.Projects.Item.Folders.Item.WithFolder_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFolder_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{project%2Did}/folders/{folder_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.ACC.FileManagement.Projects.Item.Folders.Item.WithFolder_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFolder_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{project%2Did}/folders/{folder_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
