// <auto-generated/>
#pragma warning disable CS0618
using Autodesk.DataManagement.Data.V1.Projects.Item.Commands;
using Autodesk.DataManagement.Data.V1.Projects.Item.Downloads;
using Autodesk.DataManagement.Data.V1.Projects.Item.Folders;
using Autodesk.DataManagement.Data.V1.Projects.Item.Items;
using Autodesk.DataManagement.Data.V1.Projects.Item.Jobs;
using Autodesk.DataManagement.Data.V1.Projects.Item.Storage;
using Autodesk.DataManagement.Data.V1.Projects.Item.Versions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Autodesk.DataManagement.Data.V1.Projects.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \data\v1\projects\{project_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProject_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The commands property</summary>
        public global::Autodesk.DataManagement.Data.V1.Projects.Item.Commands.CommandsRequestBuilder Commands
        {
            get => new global::Autodesk.DataManagement.Data.V1.Projects.Item.Commands.CommandsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The downloads property</summary>
        public global::Autodesk.DataManagement.Data.V1.Projects.Item.Downloads.DownloadsRequestBuilder Downloads
        {
            get => new global::Autodesk.DataManagement.Data.V1.Projects.Item.Downloads.DownloadsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The folders property</summary>
        public global::Autodesk.DataManagement.Data.V1.Projects.Item.Folders.FoldersRequestBuilder Folders
        {
            get => new global::Autodesk.DataManagement.Data.V1.Projects.Item.Folders.FoldersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The items property</summary>
        public global::Autodesk.DataManagement.Data.V1.Projects.Item.Items.ItemsRequestBuilder Items
        {
            get => new global::Autodesk.DataManagement.Data.V1.Projects.Item.Items.ItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jobs property</summary>
        public global::Autodesk.DataManagement.Data.V1.Projects.Item.Jobs.JobsRequestBuilder Jobs
        {
            get => new global::Autodesk.DataManagement.Data.V1.Projects.Item.Jobs.JobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The storage property</summary>
        public global::Autodesk.DataManagement.Data.V1.Projects.Item.Storage.StorageRequestBuilder Storage
        {
            get => new global::Autodesk.DataManagement.Data.V1.Projects.Item.Storage.StorageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The versions property</summary>
        public global::Autodesk.DataManagement.Data.V1.Projects.Item.Versions.VersionsRequestBuilder Versions
        {
            get => new global::Autodesk.DataManagement.Data.V1.Projects.Item.Versions.VersionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.DataManagement.Data.V1.Projects.Item.WithProject_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProject_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data/v1/projects/{project_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.DataManagement.Data.V1.Projects.Item.WithProject_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProject_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data/v1/projects/{project_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
