// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.FileManagement.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public enum AttributeCreated_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "string")]
        #pragma warning disable CS1591
        String,
        #pragma warning restore CS1591
        [EnumMember(Value = "date")]
        #pragma warning disable CS1591
        Date,
        #pragma warning restore CS1591
        [EnumMember(Value = "array")]
        #pragma warning disable CS1591
        Array,
        #pragma warning restore CS1591
    }
}
