// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.Issues.Projects.Item.Issues
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetFieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "displayId")]
        #pragma warning disable CS1591
        DisplayId,
        #pragma warning restore CS1591
        [EnumMember(Value = "title")]
        #pragma warning disable CS1591
        Title,
        #pragma warning restore CS1591
        [EnumMember(Value = "description")]
        #pragma warning disable CS1591
        Description,
        #pragma warning restore CS1591
        [EnumMember(Value = "issueTypeId")]
        #pragma warning disable CS1591
        IssueTypeId,
        #pragma warning restore CS1591
        [EnumMember(Value = "issueSubtypeId")]
        #pragma warning disable CS1591
        IssueSubtypeId,
        #pragma warning restore CS1591
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
        [EnumMember(Value = "assignedTo")]
        #pragma warning disable CS1591
        AssignedTo,
        #pragma warning restore CS1591
        [EnumMember(Value = "assignedToType")]
        #pragma warning disable CS1591
        AssignedToType,
        #pragma warning restore CS1591
        [EnumMember(Value = "dueDate")]
        #pragma warning disable CS1591
        DueDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "startDate")]
        #pragma warning disable CS1591
        StartDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "locationId")]
        #pragma warning disable CS1591
        LocationId,
        #pragma warning restore CS1591
        [EnumMember(Value = "locationDetails")]
        #pragma warning disable CS1591
        LocationDetails,
        #pragma warning restore CS1591
        [EnumMember(Value = "rootCauseTitle")]
        #pragma warning disable CS1591
        RootCauseTitle,
        #pragma warning restore CS1591
        [EnumMember(Value = "rootCauseId")]
        #pragma warning disable CS1591
        RootCauseId,
        #pragma warning restore CS1591
        [EnumMember(Value = "permittedStatuses")]
        #pragma warning disable CS1591
        PermittedStatuses,
        #pragma warning restore CS1591
        [EnumMember(Value = "permittedAttributes")]
        #pragma warning disable CS1591
        PermittedAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "permittedActions")]
        #pragma warning disable CS1591
        PermittedActions,
        #pragma warning restore CS1591
        [EnumMember(Value = "published")]
        #pragma warning disable CS1591
        Published,
        #pragma warning restore CS1591
        [EnumMember(Value = "commentCount")]
        #pragma warning disable CS1591
        CommentCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "openedBy")]
        #pragma warning disable CS1591
        OpenedBy,
        #pragma warning restore CS1591
        [EnumMember(Value = "openedAt")]
        #pragma warning disable CS1591
        OpenedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "closedBy")]
        #pragma warning disable CS1591
        ClosedBy,
        #pragma warning restore CS1591
        [EnumMember(Value = "closedAt")]
        #pragma warning disable CS1591
        ClosedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "createdBy")]
        #pragma warning disable CS1591
        CreatedBy,
        #pragma warning restore CS1591
        [EnumMember(Value = "createdAt")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updatedBy")]
        #pragma warning disable CS1591
        UpdatedBy,
        #pragma warning restore CS1591
        [EnumMember(Value = "updatedAt")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "customAttributes")]
        #pragma warning disable CS1591
        CustomAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "gpsCoordinates")]
        #pragma warning disable CS1591
        GpsCoordinates,
        #pragma warning restore CS1591
    }
}
