// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.RFIs.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    /// <summary>The type of attachment URN. Possible values:``dm`` - for a BIM 360 Document Management file``oss`` - for a local file</summary>
    public enum Attachment_urnType
    {
        [EnumMember(Value = "oss")]
        #pragma warning disable CS1591
        Oss,
        #pragma warning restore CS1591
        [EnumMember(Value = "dm")]
        #pragma warning disable CS1591
        Dm,
        #pragma warning restore CS1591
    }
}
