// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.RFIs.Models {
    /// <summary>The type of pushpin.</summary>
    public enum RfiBase_pushpinAttributes_type
    {
        [EnumMember(Value = "TwoDRasterPushpin")]
        TwoDRasterPushpin,
        [EnumMember(Value = "TwoDVectorPushpin")]
        TwoDVectorPushpin,
    }
}
