// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.DataManagement.OSS.Models {
    /// <summary>Policy values: `transient`, `temporary` or `persistent`</summary>
    public enum Buckets_items_policyKey
    {
        [EnumMember(Value = "transient")]
        Transient,
        [EnumMember(Value = "temporary")]
        Temporary,
        [EnumMember(Value = "persistent")]
        Persistent,
    }
}
