// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.DataManagement.OSS.Models
{
    /// <summary>Indicates the status of the object. `complete` indicates a raw upload or merged resumable upload; `chunked` indicates an unmerged resumable upload where the user  provide `public-resource-fallback`=`false`; `fallback` indicates an unmerged resumable  upload where the user provides `public-resource-fallback`=`true`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Signeds3download_response_status
    {
        [EnumMember(Value = "complete")]
        #pragma warning disable CS1591
        Complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "chunked")]
        #pragma warning disable CS1591
        Chunked,
        #pragma warning restore CS1591
        [EnumMember(Value = "fallback")]
        #pragma warning disable CS1591
        Fallback,
        #pragma warning restore CS1591
    }
}
