// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.AccountAdmin.Models {
    /// <summary>The time zone in which this project is located.</summary>
    public enum Project_timezone {
        [EnumMember(Value = "Pacific/Honolulu")]
        PacificHonolulu,
        [EnumMember(Value = "America/Juneau")]
        AmericaJuneau,
        [EnumMember(Value = "America/Los_Angeles")]
        AmericaLos_Angeles,
        [EnumMember(Value = "America/Phoenix")]
        AmericaPhoenix,
        [EnumMember(Value = "America/Denver")]
        AmericaDenver,
        [EnumMember(Value = "America/Chicago")]
        AmericaChicago,
        [EnumMember(Value = "America/New_York")]
        AmericaNew_York,
        [EnumMember(Value = "America/Indiana/Indianapolis")]
        AmericaIndianaIndianapolis,
        [EnumMember(Value = "Pacific/Pago_Pago")]
        PacificPago_Pago,
        [EnumMember(Value = "Pacific/Midway")]
        PacificMidway,
        [EnumMember(Value = "America/Tijuana")]
        AmericaTijuana,
        [EnumMember(Value = "America/Chihuahua")]
        AmericaChihuahua,
        [EnumMember(Value = "America/Mazatlan")]
        AmericaMazatlan,
        [EnumMember(Value = "America/Guatemala")]
        AmericaGuatemala,
        [EnumMember(Value = "America/Mexico_City")]
        AmericaMexico_City,
        [EnumMember(Value = "America/Monterrey")]
        AmericaMonterrey,
        [EnumMember(Value = "America/Regina")]
        AmericaRegina,
        [EnumMember(Value = "America/Bogota")]
        AmericaBogota,
        [EnumMember(Value = "America/Lima")]
        AmericaLima,
        [EnumMember(Value = "America/Caracas")]
        AmericaCaracas,
        [EnumMember(Value = "America/Halifax")]
        AmericaHalifax,
        [EnumMember(Value = "America/Guyana")]
        AmericaGuyana,
        [EnumMember(Value = "America/La_Paz")]
        AmericaLa_Paz,
        [EnumMember(Value = "America/Santiago")]
        AmericaSantiago,
        [EnumMember(Value = "America/St_Johns")]
        AmericaSt_Johns,
        [EnumMember(Value = "America/Sao_Paulo")]
        AmericaSao_Paulo,
        [EnumMember(Value = "America/Argentina/Buenos_Aires")]
        AmericaArgentinaBuenos_Aires,
        [EnumMember(Value = "America/Godthab")]
        AmericaGodthab,
        [EnumMember(Value = "Atlantic/South_Georgia")]
        AtlanticSouth_Georgia,
        [EnumMember(Value = "Atlantic/Azores")]
        AtlanticAzores,
        [EnumMember(Value = "Atlantic/Cape_Verde")]
        AtlanticCape_Verde,
        [EnumMember(Value = "Africa/Casablanca")]
        AfricaCasablanca,
        [EnumMember(Value = "Europe/Dublin")]
        EuropeDublin,
        [EnumMember(Value = "Europe/Lisbon")]
        EuropeLisbon,
        [EnumMember(Value = "Europe/London")]
        EuropeLondon,
        [EnumMember(Value = "Africa/Monrovia")]
        AfricaMonrovia,
        [EnumMember(Value = "Etc/UTC")]
        EtcUTC,
        [EnumMember(Value = "Europe/Amsterdam")]
        EuropeAmsterdam,
        [EnumMember(Value = "Europe/Belgrade")]
        EuropeBelgrade,
        [EnumMember(Value = "Europe/Berlin")]
        EuropeBerlin,
        [EnumMember(Value = "Europe/Bratislava")]
        EuropeBratislava,
        [EnumMember(Value = "Europe/Brussels")]
        EuropeBrussels,
        [EnumMember(Value = "Europe/Budapest")]
        EuropeBudapest,
        [EnumMember(Value = "Europe/Copenhagen")]
        EuropeCopenhagen,
        [EnumMember(Value = "Europe/Ljubljana")]
        EuropeLjubljana,
        [EnumMember(Value = "Europe/Madrid")]
        EuropeMadrid,
        [EnumMember(Value = "Europe/Paris")]
        EuropeParis,
        [EnumMember(Value = "Europe/Prague")]
        EuropePrague,
        [EnumMember(Value = "Europe/Rome")]
        EuropeRome,
        [EnumMember(Value = "Europe/Sarajevo")]
        EuropeSarajevo,
        [EnumMember(Value = "Europe/Skopje")]
        EuropeSkopje,
        [EnumMember(Value = "Europe/Stockholm")]
        EuropeStockholm,
        [EnumMember(Value = "Europe/Vienna")]
        EuropeVienna,
        [EnumMember(Value = "Europe/Warsaw")]
        EuropeWarsaw,
        [EnumMember(Value = "Africa/Algiers")]
        AfricaAlgiers,
        [EnumMember(Value = "Europe/Zagreb")]
        EuropeZagreb,
        [EnumMember(Value = "Europe/Athens")]
        EuropeAthens,
        [EnumMember(Value = "Europe/Bucharest")]
        EuropeBucharest,
        [EnumMember(Value = "Africa/Cairo")]
        AfricaCairo,
        [EnumMember(Value = "Africa/Harare")]
        AfricaHarare,
        [EnumMember(Value = "Europe/Helsinki")]
        EuropeHelsinki,
        [EnumMember(Value = "Europe/Istanbul")]
        EuropeIstanbul,
        [EnumMember(Value = "Asia/Jerusalem")]
        AsiaJerusalem,
        [EnumMember(Value = "Europe/Kiev")]
        EuropeKiev,
        [EnumMember(Value = "Africa/Johannesburg")]
        AfricaJohannesburg,
        [EnumMember(Value = "Europe/Riga")]
        EuropeRiga,
        [EnumMember(Value = "Europe/Sofia")]
        EuropeSofia,
        [EnumMember(Value = "Europe/Tallinn")]
        EuropeTallinn,
        [EnumMember(Value = "Europe/Vilnius")]
        EuropeVilnius,
        [EnumMember(Value = "Asia/Baghdad")]
        AsiaBaghdad,
        [EnumMember(Value = "Asia/Kuwait")]
        AsiaKuwait,
        [EnumMember(Value = "Europe/Minsk")]
        EuropeMinsk,
        [EnumMember(Value = "Africa/Nairobi")]
        AfricaNairobi,
        [EnumMember(Value = "Asia/Riyadh")]
        AsiaRiyadh,
        [EnumMember(Value = "Asia/Tehran")]
        AsiaTehran,
        [EnumMember(Value = "Asia/Muscat")]
        AsiaMuscat,
        [EnumMember(Value = "Asia/Baku")]
        AsiaBaku,
        [EnumMember(Value = "Europe/Moscow")]
        EuropeMoscow,
        [EnumMember(Value = "Asia/Tbilisi")]
        AsiaTbilisi,
        [EnumMember(Value = "Asia/Yerevan")]
        AsiaYerevan,
        [EnumMember(Value = "Asia/Kabul")]
        AsiaKabul,
        [EnumMember(Value = "Asia/Karachi")]
        AsiaKarachi,
        [EnumMember(Value = "Asia/Tashkent")]
        AsiaTashkent,
        [EnumMember(Value = "Asia/Kolkata")]
        AsiaKolkata,
        [EnumMember(Value = "Asia/Colombo")]
        AsiaColombo,
        [EnumMember(Value = "Asia/Kathmandu")]
        AsiaKathmandu,
        [EnumMember(Value = "Asia/Almaty")]
        AsiaAlmaty,
        [EnumMember(Value = "Asia/Dhaka")]
        AsiaDhaka,
        [EnumMember(Value = "Asia/Yekaterinburg")]
        AsiaYekaterinburg,
        [EnumMember(Value = "Asia/Rangoon")]
        AsiaRangoon,
        [EnumMember(Value = "Asia/Bangkok")]
        AsiaBangkok,
        [EnumMember(Value = "Asia/Jakarta")]
        AsiaJakarta,
        [EnumMember(Value = "Asia/Novosibirsk")]
        AsiaNovosibirsk,
        [EnumMember(Value = "Asia/Shanghai")]
        AsiaShanghai,
        [EnumMember(Value = "Asia/Chongqing")]
        AsiaChongqing,
        [EnumMember(Value = "Asia/Hong_Kong")]
        AsiaHong_Kong,
        [EnumMember(Value = "Asia/Krasnoyarsk")]
        AsiaKrasnoyarsk,
        [EnumMember(Value = "Asia/Kuala_Lumpur")]
        AsiaKuala_Lumpur,
        [EnumMember(Value = "Australia/Perth")]
        AustraliaPerth,
        [EnumMember(Value = "Asia/Singapore")]
        AsiaSingapore,
        [EnumMember(Value = "Asia/Taipei")]
        AsiaTaipei,
        [EnumMember(Value = "Asia/Ulaanbaatar")]
        AsiaUlaanbaatar,
        [EnumMember(Value = "Asia/Urumqi")]
        AsiaUrumqi,
        [EnumMember(Value = "Asia/Irkutsk")]
        AsiaIrkutsk,
        [EnumMember(Value = "Asia/Tokyo")]
        AsiaTokyo,
        [EnumMember(Value = "Asia/Seoul")]
        AsiaSeoul,
        [EnumMember(Value = "Australia/Adelaide")]
        AustraliaAdelaide,
        [EnumMember(Value = "Australia/Darwin")]
        AustraliaDarwin,
        [EnumMember(Value = "Australia/Brisbane")]
        AustraliaBrisbane,
        [EnumMember(Value = "Australia/Melbourne")]
        AustraliaMelbourne,
        [EnumMember(Value = "Pacific/Guam")]
        PacificGuam,
        [EnumMember(Value = "Australia/Hobart")]
        AustraliaHobart,
        [EnumMember(Value = "Pacific/Port_Moresby")]
        PacificPort_Moresby,
        [EnumMember(Value = "Australia/Sydney")]
        AustraliaSydney,
        [EnumMember(Value = "Asia/Yakutsk")]
        AsiaYakutsk,
        [EnumMember(Value = "Pacific/Noumea")]
        PacificNoumea,
        [EnumMember(Value = "Asia/Vladivostok")]
        AsiaVladivostok,
        [EnumMember(Value = "Pacific/Auckland")]
        PacificAuckland,
        [EnumMember(Value = "Pacific/Fiji")]
        PacificFiji,
        [EnumMember(Value = "Asia/Kamchatka")]
        AsiaKamchatka,
        [EnumMember(Value = "Asia/Magadan")]
        AsiaMagadan,
        [EnumMember(Value = "Pacific/Majuro")]
        PacificMajuro,
        [EnumMember(Value = "Pacific/Guadalcanal")]
        PacificGuadalcanal,
        [EnumMember(Value = "Pacific/Tongatapu")]
        PacificTongatapu,
        [EnumMember(Value = "Pacific/Apia")]
        PacificApia,
        [EnumMember(Value = "Pacific/Fakaofo")]
        PacificFakaofo,
    }
}
