// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.AccountAdmin.Models {
    /// <summary>The status of the service in the project.  Valid values are `active`, `activating`, `available`,`inactive`, `deactivating`, `activationFailed` and `deactivationFailed`.</summary>
    public enum Project_services_status {
        [EnumMember(Value = "active")]
        Active,
        [EnumMember(Value = "activating")]
        Activating,
        [EnumMember(Value = "available")]
        Available,
        [EnumMember(Value = "inactive")]
        Inactive,
        [EnumMember(Value = "deactivating")]
        Deactivating,
        [EnumMember(Value = "activationFailed")]
        ActivationFailed,
        [EnumMember(Value = "deactivationFailed")]
        DeactivationFailed,
    }
}
