// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.AccountAdmin.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    /// <summary>The user access to the product. The valid values are: `administrator`, `member` and `none`.</summary>
    public enum Users_access
    {
        [EnumMember(Value = "administrator")]
        #pragma warning disable CS1591
        Administrator,
        #pragma warning restore CS1591
        [EnumMember(Value = "member")]
        #pragma warning disable CS1591
        Member,
        #pragma warning restore CS1591
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
    }
}
