// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ModelDerivative.Models
{
    /// <summary>Specifies the materials to apply to the generated SVF derivatives. Available options are:- auto - (Default) Use the current setting of the default view of the input file.- basic - Use basic materials.- autodesk - Use Autodesk materials.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum JobPayloadFormat_advanced_materialMode
    {
        [EnumMember(Value = "auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
        [EnumMember(Value = "basic")]
        #pragma warning disable CS1591
        Basic,
        #pragma warning restore CS1591
        [EnumMember(Value = "autodesk")]
        #pragma warning disable CS1591
        Autodesk,
        #pragma warning restore CS1591
    }
}
