// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.Vault.Models
{
    /// <summary>The classification of the file.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FileClassificationEnum
    {
        [EnumMember(Value = "None")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "DesignVisualization")]
        #pragma warning disable CS1591
        DesignVisualization,
        #pragma warning restore CS1591
        [EnumMember(Value = "DesignDocument")]
        #pragma warning disable CS1591
        DesignDocument,
        #pragma warning restore CS1591
        [EnumMember(Value = "ConfigurationMember")]
        #pragma warning disable CS1591
        ConfigurationMember,
        #pragma warning restore CS1591
        [EnumMember(Value = "ConfigurationFactory")]
        #pragma warning disable CS1591
        ConfigurationFactory,
        #pragma warning restore CS1591
        [EnumMember(Value = "ElectricalProject")]
        #pragma warning disable CS1591
        ElectricalProject,
        #pragma warning restore CS1591
        [EnumMember(Value = "DesignSubstitute")]
        #pragma warning disable CS1591
        DesignSubstitute,
        #pragma warning restore CS1591
        [EnumMember(Value = "DesignRepresentation")]
        #pragma warning disable CS1591
        DesignRepresentation,
        #pragma warning restore CS1591
        [EnumMember(Value = "DesignPresentation")]
        #pragma warning disable CS1591
        DesignPresentation,
        #pragma warning restore CS1591
    }
}
