// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.Vault.Models
{
    /// <summary>File association options.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FileAssociationTypeEnum
    {
        [EnumMember(Value = "Dependency")]
        #pragma warning disable CS1591
        Dependency,
        #pragma warning restore CS1591
        [EnumMember(Value = "Attachment")]
        #pragma warning disable CS1591
        Attachment,
        #pragma warning restore CS1591
    }
}
