// <auto-generated/>
using Autodesk.ACC.ModelProperties.V2.Projects.Item.Diffs.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Autodesk.ACC.ModelProperties.V2.Projects.Item.Diffs
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\projects\{projectId}\diffs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class DiffsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Autodesk.ACC.ModelProperties.v2.projects.item.diffs.item collection</summary>
        /// <param name="position">The diff ID.</param>
        /// <returns>A <see cref="global::Autodesk.ACC.ModelProperties.V2.Projects.Item.Diffs.Item.WithDiffItemRequestBuilder"/></returns>
        public global::Autodesk.ACC.ModelProperties.V2.Projects.Item.Diffs.Item.WithDiffItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("diffId", position);
                return new global::Autodesk.ACC.ModelProperties.V2.Projects.Item.Diffs.Item.WithDiffItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.ACC.ModelProperties.V2.Projects.Item.Diffs.DiffsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DiffsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/projects/{projectId}/diffs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.ACC.ModelProperties.V2.Projects.Item.Diffs.DiffsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DiffsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/projects/{projectId}/diffs", rawUrl)
        {
        }
    }
}
