// <auto-generated/>
using Autodesk.ACC.CostManagement.V1.Projects.Item.WorkflowConditions.Reorder.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Autodesk.ACC.CostManagement.V1.Projects.Item.WorkflowConditions.Reorder {
    /// <summary>
    /// Builds and executes requests for operations under \v1\projects\{projectId}\workflow-conditions\:reorder
    /// </summary>
    public class WorkflowConditionsReorderRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>Gets an item from the Autodesk.ACC.CostManagement.v1.projects.item.workflowConditions.Reorder.item collection</summary>
        /// <param name="position">The associated module.</param>
        /// <returns>A <see cref="WithAssociationTypeItemRequestBuilder"/></returns>
        public WithAssociationTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("associationType", position);
                return new WithAssociationTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="WorkflowConditionsReorderRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkflowConditionsReorderRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/projects/{projectId}/workflow-conditions/:reorder", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="WorkflowConditionsReorderRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkflowConditionsReorderRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/projects/{projectId}/workflow-conditions/:reorder", rawUrl)
        {
        }
    }
}
