name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish:
    runs-on: windows-latest  # Use a Windows runner to build .NET projects

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'  # Specify your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Get Version
        id: get_version
        
        run: |
          $VERSION = "${{ github.ref }}" -replace 'refs/tags/v', ''
          echo "::set-output name=version::$VERSION" 

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore /p:Version=${{ steps.get_version.outputs.version }}

      - name: Pack
        run:  dotnet pack --configuration Release --no-build /p:Version=${{ steps.get_version.outputs.version }} --output ./nupkg
      
